"""
intel_roadmap.py

Format defintion for translating an Intel SOC roadmap into a GoldenRoadmap format

Author Scott Tandy
Copyright Intel Corporation 2020

"""
from collections import OrderedDict

### Roadmap Excel File Column Names
BUSINESS_COL_NAME =  'Business'
SEGMENT_COL_NAME =  'Segment'
SHAREDWITH_COL_NAME =  'SharedWith'
SPEED_ID_COL_NAME =  'Speed ID'
FAMILY_NAME_COL_NAME = 'Family Name'
NAME_COL_NAME =  'Name'
A0_TI_COL_NAME =  'A0 TI'
PRQABLE_TI_COL_NAME =  'PRQable TI'
PRQ_COL_NAME =  'PRQ'
PHASE_COL_NAME =  'Phase'
IP_FAMILY_COL_NAME =  'IP Family'
IP_FREEZE_COL_NAME =  'IP Freeze'
GFX_CONFIG_COL_NAME =  'Gfx Config'
MEDIA_IP_COL_NAME =  'Media IP'
DISPLAY_IP_COL_NAME =  'Display IP'
PROCESS_COL_NAME =  'Process'
UPDATED_COL_NAME =  'Updated'
COMMENTS_COL_NAME =  'Comments'

### BUSINESS CATEGORES
BUSINESS_DC_GPU = 'Datacenter GPU'
BUSINESS_CLIENT_GPU = 'Client GPU'
BUSINESS_CLIENT_INTEGRATED = 'Client'
BUSINESS_DC_CPU = 'Datacenter CPU'

### DC_GPU Segments
SEGMENT_DC_GPU_COMPUTE = 'Compute'
SEGMENT_DC_GPU_MULTI_USE = 'Multi-Use'
DC_GPU_SEGMENT_ORDER = [SEGMENT_DC_GPU_COMPUTE, SEGMENT_DC_GPU_MULTI_USE]

### Client GPU Segments
SEGMENT_CLIENT_GPU_PRO = 'Pro'
SEGMENT_CLIENT_GPU_ENTHUSIAST = 'Enthusiast'
SEGMENT_CLIENT_GPU_PERFORMANCE = 'Performance'
SEGMENT_CLIENT_GPU_MAINSTREAM = 'Mainstream'
SEGMENT_CLIENT_GPU_ENTRY = 'Entry'
CLIENT_GPU_SGMENT_ORDER = [SEGMENT_CLIENT_GPU_PRO, SEGMENT_CLIENT_GPU_ENTHUSIAST,\
    SEGMENT_CLIENT_GPU_PERFORMANCE, SEGMENT_CLIENT_GPU_MAINSTREAM, SEGMENT_CLIENT_GPU_ENTRY]

ROADMAP_DISCRETE_GRAPHICS_BUSINESS_ORDER = [BUSINESS_DC_GPU, BUSINESS_CLIENT_GPU]
